/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as c151 from "./C151";
export { GIC__factory } from "./GIC__factory";
export { GICGovernor__factory } from "./GICGovernor__factory";
export { GICRegistry__factory } from "./GICRegistry__factory";
