# .opencode/workflow-template.yaml
# Kaizen PR Council — AUREA ➜ HERMES ➜ EVE ➜ JADE

version: 1
name: "Kaizen PR Council — AUREA ➜ HERMES ➜ EVE ➜ JADE"

triggers:
  # run on PR open/sync/comment: /council
  on:
    - pull_request.opened
    - pull_request.synchronize
    - pull_request.reopened
    - comment.command:/council

context:
  repo_paths:
    docs_index: "docs/README.md"
    echo_docs: "docs/architecture/ECHO_LAYER_CANON.md"
    config_units: "configs/integrity_units.yaml"
    broker_app: "apps/broker-api"
    echo_services: "apps/broker-api/src/services/echo"
    units_pkg: "packages/integrity-units"
  env:
    SHARDS_PER_CREDIT: "1000000"
    ECHO_STRICT_GI: "0.97"
  labels:
    needs-council: "council:pending"
    council-passed: "council:approved"
    council-blocked: "council:blocked"

flow:
  - id: aurea-architect
    agent: AUREA
    goal: >
      Structural & safety review for GI-governed systems. Ensure ECHO Layer, ledger
      migrations, and integrity configs stay coherent with Trinity rules.
    inputs:
      - diff
      - file:${context.repo_paths.config_units}
      - file:${context.repo_paths.echo_docs}
      - tree:${context.repo_paths.echo_services}
      - tree:${context.repo_paths.broker_app}
    checks:
      required:
        - name: "Integrity units parse"
          run: "yq '${.}' ${context.repo_paths.config_units} >/dev/null"
        - name: "Broker API lint + type-check"
          run: "npm run lint --workspace=${context.repo_paths.broker_app} && npm run type-check --workspace=${context.repo_paths.broker_app}"
        - name: "Broker API builds"
          run: "npm run build --workspace=${context.repo_paths.broker_app}"
        - name: "Integrity + consensus pipelines"
          run: "npm run lint && npm run type-check && npm run integrity:check && npm run consensus:validate"
    decision:
      pass_label: ${context.labels.needs-council}
      comment_style: pr_comment_style
      fail_hard: true   # stop flow if AUREA blocks

  - id: hermes-ops
    agent: HERMES
    goal: >
      Ops risk review for ECHO caching + DVA.LITE pipelines. Track CI time, memory,
      sentinel costs, and cache hit regressions. Suggest concrete diffs.
    inputs:
      - diff
      - ci_logs
    checks:
      optional:
        - name: "Broker API unit tests"
          run: "npm run test --workspace=${context.repo_paths.broker_app} || true"
        - name: "ECHO validator smoke"
          run: "npm run sentinel:health || true"
    decision:
      annotate_inline: true
      comment_style: pr_comment_style

  - id: eve-civic-audit
    agent: EVE
    goal: >
      Policy, licensing, accessibility, and civic documentation.
      Ensure new ECHO/Labor endpoints & math are human-readable.
    inputs:
      - diff
      - file:${context.repo_paths.docs_index}
      - file:${context.repo_paths.echo_docs}
    actions:
      - when_missing:
          path: ${context.repo_paths.docs_index}
          create_file: |
            # Kaizen OS Documentation Index
            (autogenerated by EVE — please fill in details)
    decision:
      add_checklist: true
      comment_style: pr_comment_style

  - id: jade-morale
    agent: JADE
    goal: >
      Summarize intent in plain language, list possible confusions,
      and leave encouragement + next micro-step.
    inputs:
      - diff
      - thread
    decision:
      sticky_comment: true
      comment_style: pr_comment_style

quorum_rules:
  # AUREA has veto; otherwise council passes when 3/4 are non-blocking.
  hard_veto:
    - aurea-architect
  pass_when:
    any_of:
      - ids: [aurea-architect, hermes-ops, eve-civic-audit]
        min_success: 2

outcomes:
  on_pass:
    set_labels: [${context.labels.council-passed}]
    remove_labels: [${context.labels.needs-council}, ${context.labels.council-blocked}]
    comment: "✅ Council approves. Integrity flows steady."
  on_block:
    set_labels: [${context.labels.council-blocked}]
    remove_labels: [${context.labels.needs-council}, ${context.labels.council-passed}]
    comment: "🛑 Council blocked — see AUREA's notes above."
  on_pending:
    ensure_label: ${context.labels.needs-council}

commands:
  # Handy chat commands inside PR comments
  - name: "/council"
    description: "Re-run the Kaizen PR Council"
    run_flow: [aurea-architect, hermes-ops, eve-civic-audit, jade-morale]
  - name: "/aurea"
    run_flow: [aurea-architect]
  - name: "/hermes"
    run_flow: [hermes-ops]
  - name: "/eve"
    run_flow: [eve-civic-audit]
  - name: "/jade"
    run_flow: [jade-morale]
