openapi: 3.1.0
info: { title: Civic Ledger API, version: '0.1' }
paths:
  /ledger/attest:
    post:
      summary: Submit attestation
      requestBody:
        required: true
        content: { application/json: { schema: { type: object, properties: { hash: {type: string}, meta: {type: object} } } } }
      responses: { '200': { description: OK } }
  /ledger/gi:
    get: { summary: Get global integrity, responses: { '200': { description: OK } } }

