/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace CoordinationMIC {
  export type SentinelAttestationStruct = {
    score: BigNumberish;
    timestamp: BigNumberish;
    cathedral: string;
    reward: BigNumberish;
  };

  export type SentinelAttestationStructOutput = [
    score: bigint,
    timestamp: bigint,
    cathedral: string,
    reward: bigint
  ] & { score: bigint; timestamp: bigint; cathedral: string; reward: bigint };
}

export interface CoordinationMICInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "K"
      | "L"
      | "MAX_SCORE"
      | "MIN_SCORE"
      | "X0"
      | "allowance"
      | "approve"
      | "assignSentinel"
      | "attest"
      | "attestations"
      | "authorizedAttesters"
      | "balanceOf"
      | "cathedrals"
      | "configureCathedral"
      | "currentCycle"
      | "decimals"
      | "getAttestation"
      | "getCathedralMultiplier"
      | "getSentinelCathedral"
      | "name"
      | "owner"
      | "previewReward"
      | "renounceOwnership"
      | "sentinelCathedrals"
      | "setAttester"
      | "symbol"
      | "totalAttestations"
      | "totalSupply"
      | "transfer"
      | "transferFrom"
      | "transferOwnership"
      | "updateCycle"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Approval"
      | "AttestationSubmitted"
      | "AttesterAuthorized"
      | "CathedralConfigured"
      | "CycleUpdated"
      | "OwnershipTransferred"
      | "SentinelAssigned"
      | "Transfer"
  ): EventFragment;

  encodeFunctionData(functionFragment: "K", values?: undefined): string;
  encodeFunctionData(functionFragment: "L", values?: undefined): string;
  encodeFunctionData(functionFragment: "MAX_SCORE", values?: undefined): string;
  encodeFunctionData(functionFragment: "MIN_SCORE", values?: undefined): string;
  encodeFunctionData(functionFragment: "X0", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "allowance",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "assignSentinel",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "attest",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "attestations",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedAttesters",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "cathedrals", values: [string]): string;
  encodeFunctionData(
    functionFragment: "configureCathedral",
    values: [string, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "currentCycle",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getAttestation",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getCathedralMultiplier",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getSentinelCathedral",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "previewReward",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sentinelCathedrals",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setAttester",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalAttestations",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "updateCycle", values: [string]): string;

  decodeFunctionResult(functionFragment: "K", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "L", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MAX_SCORE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MIN_SCORE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "X0", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "assignSentinel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "attest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "attestations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedAttesters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cathedrals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "configureCathedral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentCycle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAttestation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCathedralMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSentinelCathedral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "previewReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sentinelCathedrals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAttester",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalAttestations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCycle",
    data: BytesLike
  ): Result;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    spender: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [owner: string, spender: string, value: bigint];
  export interface OutputObject {
    owner: string;
    spender: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AttestationSubmittedEvent {
  export type InputTuple = [
    sentinelId: string,
    score: BigNumberish,
    reward: BigNumberish,
    cathedral: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    sentinelId: string,
    score: bigint,
    reward: bigint,
    cathedral: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    sentinelId: string;
    score: bigint;
    reward: bigint;
    cathedral: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AttesterAuthorizedEvent {
  export type InputTuple = [attester: AddressLike, authorized: boolean];
  export type OutputTuple = [attester: string, authorized: boolean];
  export interface OutputObject {
    attester: string;
    authorized: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CathedralConfiguredEvent {
  export type InputTuple = [
    cathedral: string,
    multiplier: BigNumberish,
    active: boolean
  ];
  export type OutputTuple = [
    cathedral: string,
    multiplier: bigint,
    active: boolean
  ];
  export interface OutputObject {
    cathedral: string;
    multiplier: bigint;
    active: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CycleUpdatedEvent {
  export type InputTuple = [oldCycle: string, newCycle: string];
  export type OutputTuple = [oldCycle: string, newCycle: string];
  export interface OutputObject {
    oldCycle: string;
    newCycle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SentinelAssignedEvent {
  export type InputTuple = [sentinelId: string, cathedral: string];
  export type OutputTuple = [sentinelId: string, cathedral: string];
  export interface OutputObject {
    sentinelId: string;
    cathedral: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, value: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CoordinationMIC extends BaseContract {
  connect(runner?: ContractRunner | null): CoordinationMIC;
  waitForDeployment(): Promise<this>;

  interface: CoordinationMICInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  K: TypedContractMethod<[], [bigint], "view">;

  L: TypedContractMethod<[], [bigint], "view">;

  MAX_SCORE: TypedContractMethod<[], [bigint], "view">;

  MIN_SCORE: TypedContractMethod<[], [bigint], "view">;

  X0: TypedContractMethod<[], [bigint], "view">;

  allowance: TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;

  approve: TypedContractMethod<
    [spender: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  assignSentinel: TypedContractMethod<
    [sentinelId: string, cathedral: string],
    [void],
    "nonpayable"
  >;

  attest: TypedContractMethod<
    [sentinelId: string, coordinationScore: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  attestations: TypedContractMethod<
    [arg0: string],
    [
      [bigint, bigint, string, bigint] & {
        score: bigint;
        timestamp: bigint;
        cathedral: string;
        reward: bigint;
      }
    ],
    "view"
  >;

  authorizedAttesters: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  balanceOf: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  cathedrals: TypedContractMethod<
    [arg0: string],
    [[bigint, boolean] & { multiplier: bigint; active: boolean }],
    "view"
  >;

  configureCathedral: TypedContractMethod<
    [cathedral: string, multiplier: BigNumberish, active: boolean],
    [void],
    "nonpayable"
  >;

  currentCycle: TypedContractMethod<[], [string], "view">;

  decimals: TypedContractMethod<[], [bigint], "view">;

  getAttestation: TypedContractMethod<
    [sentinelId: string],
    [CoordinationMIC.SentinelAttestationStructOutput],
    "view"
  >;

  getCathedralMultiplier: TypedContractMethod<
    [cathedral: string],
    [bigint],
    "view"
  >;

  getSentinelCathedral: TypedContractMethod<
    [sentinelId: string],
    [string],
    "view"
  >;

  name: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  previewReward: TypedContractMethod<
    [sentinelId: string, coordinationScore: BigNumberish],
    [bigint],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  sentinelCathedrals: TypedContractMethod<[arg0: string], [string], "view">;

  setAttester: TypedContractMethod<
    [attester: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  totalAttestations: TypedContractMethod<[], [bigint], "view">;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  transfer: TypedContractMethod<
    [to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateCycle: TypedContractMethod<[newCycle: string], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(nameOrSignature: "K"): TypedContractMethod<[], [bigint], "view">;
  getFunction(nameOrSignature: "L"): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_SCORE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_SCORE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(nameOrSignature: "X0"): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "allowance"
  ): TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [spender: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "assignSentinel"
  ): TypedContractMethod<
    [sentinelId: string, cathedral: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "attest"
  ): TypedContractMethod<
    [sentinelId: string, coordinationScore: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "attestations"
  ): TypedContractMethod<
    [arg0: string],
    [
      [bigint, bigint, string, bigint] & {
        score: bigint;
        timestamp: bigint;
        cathedral: string;
        reward: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "authorizedAttesters"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "cathedrals"
  ): TypedContractMethod<
    [arg0: string],
    [[bigint, boolean] & { multiplier: bigint; active: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "configureCathedral"
  ): TypedContractMethod<
    [cathedral: string, multiplier: BigNumberish, active: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "currentCycle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "decimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAttestation"
  ): TypedContractMethod<
    [sentinelId: string],
    [CoordinationMIC.SentinelAttestationStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCathedralMultiplier"
  ): TypedContractMethod<[cathedral: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSentinelCathedral"
  ): TypedContractMethod<[sentinelId: string], [string], "view">;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "previewReward"
  ): TypedContractMethod<
    [sentinelId: string, coordinationScore: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sentinelCathedrals"
  ): TypedContractMethod<[arg0: string], [string], "view">;
  getFunction(
    nameOrSignature: "setAttester"
  ): TypedContractMethod<
    [attester: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalAttestations"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transfer"
  ): TypedContractMethod<
    [to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateCycle"
  ): TypedContractMethod<[newCycle: string], [void], "nonpayable">;

  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "AttestationSubmitted"
  ): TypedContractEvent<
    AttestationSubmittedEvent.InputTuple,
    AttestationSubmittedEvent.OutputTuple,
    AttestationSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "AttesterAuthorized"
  ): TypedContractEvent<
    AttesterAuthorizedEvent.InputTuple,
    AttesterAuthorizedEvent.OutputTuple,
    AttesterAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "CathedralConfigured"
  ): TypedContractEvent<
    CathedralConfiguredEvent.InputTuple,
    CathedralConfiguredEvent.OutputTuple,
    CathedralConfiguredEvent.OutputObject
  >;
  getEvent(
    key: "CycleUpdated"
  ): TypedContractEvent<
    CycleUpdatedEvent.InputTuple,
    CycleUpdatedEvent.OutputTuple,
    CycleUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SentinelAssigned"
  ): TypedContractEvent<
    SentinelAssignedEvent.InputTuple,
    SentinelAssignedEvent.OutputTuple,
    SentinelAssignedEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;

  filters: {
    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "AttestationSubmitted(string,uint256,uint256,string,uint256)": TypedContractEvent<
      AttestationSubmittedEvent.InputTuple,
      AttestationSubmittedEvent.OutputTuple,
      AttestationSubmittedEvent.OutputObject
    >;
    AttestationSubmitted: TypedContractEvent<
      AttestationSubmittedEvent.InputTuple,
      AttestationSubmittedEvent.OutputTuple,
      AttestationSubmittedEvent.OutputObject
    >;

    "AttesterAuthorized(address,bool)": TypedContractEvent<
      AttesterAuthorizedEvent.InputTuple,
      AttesterAuthorizedEvent.OutputTuple,
      AttesterAuthorizedEvent.OutputObject
    >;
    AttesterAuthorized: TypedContractEvent<
      AttesterAuthorizedEvent.InputTuple,
      AttesterAuthorizedEvent.OutputTuple,
      AttesterAuthorizedEvent.OutputObject
    >;

    "CathedralConfigured(string,uint256,bool)": TypedContractEvent<
      CathedralConfiguredEvent.InputTuple,
      CathedralConfiguredEvent.OutputTuple,
      CathedralConfiguredEvent.OutputObject
    >;
    CathedralConfigured: TypedContractEvent<
      CathedralConfiguredEvent.InputTuple,
      CathedralConfiguredEvent.OutputTuple,
      CathedralConfiguredEvent.OutputObject
    >;

    "CycleUpdated(string,string)": TypedContractEvent<
      CycleUpdatedEvent.InputTuple,
      CycleUpdatedEvent.OutputTuple,
      CycleUpdatedEvent.OutputObject
    >;
    CycleUpdated: TypedContractEvent<
      CycleUpdatedEvent.InputTuple,
      CycleUpdatedEvent.OutputTuple,
      CycleUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SentinelAssigned(string,string)": TypedContractEvent<
      SentinelAssignedEvent.InputTuple,
      SentinelAssignedEvent.OutputTuple,
      SentinelAssignedEvent.OutputObject
    >;
    SentinelAssigned: TypedContractEvent<
      SentinelAssignedEvent.InputTuple,
      SentinelAssignedEvent.OutputTuple,
      SentinelAssignedEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
  };
}
