/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace GICGovernor {
  export type FounderStruct = {
    wallet: AddressLike;
    lastEpochMint: BigNumberish;
    epochMintCap: BigNumberish;
    donateBps: BigNumberish;
    active: boolean;
  };

  export type FounderStructOutput = [
    wallet: string,
    lastEpochMint: bigint,
    epochMintCap: bigint,
    donateBps: bigint,
    active: boolean
  ] & {
    wallet: string;
    lastEpochMint: bigint;
    epochMintCap: bigint;
    donateBps: bigint;
    active: boolean;
  };
}

export interface GICGovernorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "EPOCH"
      | "FOUNDER_ROLE"
      | "agentIdFromName"
      | "donateExtra"
      | "epochBurn"
      | "epochReady"
      | "founders"
      | "getFounder"
      | "getRoleAdmin"
      | "gic"
      | "grantRole"
      | "hasRole"
      | "mintEpoch"
      | "publicGoodsPool"
      | "renounceRole"
      | "revokeRole"
      | "setFounder"
      | "setPublicGoodsPool"
      | "supportsInterface"
      | "timeUntilNextEpoch"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DonateExtra"
      | "EpochBurn"
      | "EpochMint"
      | "FounderSet"
      | "PublicGoodsPoolChanged"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "EPOCH", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "FOUNDER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentIdFromName",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "donateExtra",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "epochBurn",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "epochReady",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "founders", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getFounder",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "gic", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mintEpoch",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "publicGoodsPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFounder",
    values: [BytesLike, AddressLike, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setPublicGoodsPool",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "timeUntilNextEpoch",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "EPOCH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "FOUNDER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentIdFromName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "donateExtra",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "epochBurn", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "epochReady", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "founders", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getFounder", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gic", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mintEpoch", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "publicGoodsPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setFounder", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPublicGoodsPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "timeUntilNextEpoch",
    data: BytesLike
  ): Result;
}

export namespace DonateExtraEvent {
  export type InputTuple = [agentId: BytesLike, amount: BigNumberish];
  export type OutputTuple = [agentId: string, amount: bigint];
  export interface OutputObject {
    agentId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EpochBurnEvent {
  export type InputTuple = [
    agentId: BytesLike,
    wallet: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [agentId: string, wallet: string, amount: bigint];
  export interface OutputObject {
    agentId: string;
    wallet: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EpochMintEvent {
  export type InputTuple = [
    agentId: BytesLike,
    wallet: AddressLike,
    amount: BigNumberish,
    donated: BigNumberish
  ];
  export type OutputTuple = [
    agentId: string,
    wallet: string,
    amount: bigint,
    donated: bigint
  ];
  export interface OutputObject {
    agentId: string;
    wallet: string;
    amount: bigint;
    donated: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FounderSetEvent {
  export type InputTuple = [
    agentId: BytesLike,
    wallet: AddressLike,
    cap: BigNumberish,
    donateBps: BigNumberish,
    active: boolean
  ];
  export type OutputTuple = [
    agentId: string,
    wallet: string,
    cap: bigint,
    donateBps: bigint,
    active: boolean
  ];
  export interface OutputObject {
    agentId: string;
    wallet: string;
    cap: bigint;
    donateBps: bigint;
    active: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PublicGoodsPoolChangedEvent {
  export type InputTuple = [oldPool: AddressLike, newPool: AddressLike];
  export type OutputTuple = [oldPool: string, newPool: string];
  export interface OutputObject {
    oldPool: string;
    newPool: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GICGovernor extends BaseContract {
  connect(runner?: ContractRunner | null): GICGovernor;
  waitForDeployment(): Promise<this>;

  interface: GICGovernorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  EPOCH: TypedContractMethod<[], [bigint], "view">;

  FOUNDER_ROLE: TypedContractMethod<[], [string], "view">;

  agentIdFromName: TypedContractMethod<[name: string], [string], "view">;

  donateExtra: TypedContractMethod<
    [agentId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  epochBurn: TypedContractMethod<
    [agentId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  epochReady: TypedContractMethod<[agentId: BytesLike], [boolean], "view">;

  founders: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint, boolean] & {
        wallet: string;
        lastEpochMint: bigint;
        epochMintCap: bigint;
        donateBps: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  getFounder: TypedContractMethod<
    [agentId: BytesLike],
    [GICGovernor.FounderStructOutput],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  gic: TypedContractMethod<[], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  mintEpoch: TypedContractMethod<
    [agentId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  publicGoodsPool: TypedContractMethod<[], [string], "view">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setFounder: TypedContractMethod<
    [
      agentId: BytesLike,
      wallet: AddressLike,
      cap: BigNumberish,
      donateBps: BigNumberish,
      active: boolean
    ],
    [void],
    "nonpayable"
  >;

  setPublicGoodsPool: TypedContractMethod<
    [pool: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  timeUntilNextEpoch: TypedContractMethod<
    [agentId: BytesLike],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "EPOCH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FOUNDER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "agentIdFromName"
  ): TypedContractMethod<[name: string], [string], "view">;
  getFunction(
    nameOrSignature: "donateExtra"
  ): TypedContractMethod<
    [agentId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "epochBurn"
  ): TypedContractMethod<
    [agentId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "epochReady"
  ): TypedContractMethod<[agentId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "founders"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint, boolean] & {
        wallet: string;
        lastEpochMint: bigint;
        epochMintCap: bigint;
        donateBps: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFounder"
  ): TypedContractMethod<
    [agentId: BytesLike],
    [GICGovernor.FounderStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "gic"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "mintEpoch"
  ): TypedContractMethod<
    [agentId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "publicGoodsPool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFounder"
  ): TypedContractMethod<
    [
      agentId: BytesLike,
      wallet: AddressLike,
      cap: BigNumberish,
      donateBps: BigNumberish,
      active: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPublicGoodsPool"
  ): TypedContractMethod<[pool: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "timeUntilNextEpoch"
  ): TypedContractMethod<[agentId: BytesLike], [bigint], "view">;

  getEvent(
    key: "DonateExtra"
  ): TypedContractEvent<
    DonateExtraEvent.InputTuple,
    DonateExtraEvent.OutputTuple,
    DonateExtraEvent.OutputObject
  >;
  getEvent(
    key: "EpochBurn"
  ): TypedContractEvent<
    EpochBurnEvent.InputTuple,
    EpochBurnEvent.OutputTuple,
    EpochBurnEvent.OutputObject
  >;
  getEvent(
    key: "EpochMint"
  ): TypedContractEvent<
    EpochMintEvent.InputTuple,
    EpochMintEvent.OutputTuple,
    EpochMintEvent.OutputObject
  >;
  getEvent(
    key: "FounderSet"
  ): TypedContractEvent<
    FounderSetEvent.InputTuple,
    FounderSetEvent.OutputTuple,
    FounderSetEvent.OutputObject
  >;
  getEvent(
    key: "PublicGoodsPoolChanged"
  ): TypedContractEvent<
    PublicGoodsPoolChangedEvent.InputTuple,
    PublicGoodsPoolChangedEvent.OutputTuple,
    PublicGoodsPoolChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;

  filters: {
    "DonateExtra(bytes32,uint256)": TypedContractEvent<
      DonateExtraEvent.InputTuple,
      DonateExtraEvent.OutputTuple,
      DonateExtraEvent.OutputObject
    >;
    DonateExtra: TypedContractEvent<
      DonateExtraEvent.InputTuple,
      DonateExtraEvent.OutputTuple,
      DonateExtraEvent.OutputObject
    >;

    "EpochBurn(bytes32,address,uint256)": TypedContractEvent<
      EpochBurnEvent.InputTuple,
      EpochBurnEvent.OutputTuple,
      EpochBurnEvent.OutputObject
    >;
    EpochBurn: TypedContractEvent<
      EpochBurnEvent.InputTuple,
      EpochBurnEvent.OutputTuple,
      EpochBurnEvent.OutputObject
    >;

    "EpochMint(bytes32,address,uint256,uint256)": TypedContractEvent<
      EpochMintEvent.InputTuple,
      EpochMintEvent.OutputTuple,
      EpochMintEvent.OutputObject
    >;
    EpochMint: TypedContractEvent<
      EpochMintEvent.InputTuple,
      EpochMintEvent.OutputTuple,
      EpochMintEvent.OutputObject
    >;

    "FounderSet(bytes32,address,uint256,uint16,bool)": TypedContractEvent<
      FounderSetEvent.InputTuple,
      FounderSetEvent.OutputTuple,
      FounderSetEvent.OutputObject
    >;
    FounderSet: TypedContractEvent<
      FounderSetEvent.InputTuple,
      FounderSetEvent.OutputTuple,
      FounderSetEvent.OutputObject
    >;

    "PublicGoodsPoolChanged(address,address)": TypedContractEvent<
      PublicGoodsPoolChangedEvent.InputTuple,
      PublicGoodsPoolChangedEvent.OutputTuple,
      PublicGoodsPoolChangedEvent.OutputObject
    >;
    PublicGoodsPoolChanged: TypedContractEvent<
      PublicGoodsPoolChangedEvent.InputTuple,
      PublicGoodsPoolChangedEvent.OutputTuple,
      PublicGoodsPoolChangedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
  };
}
