/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace GICRegistry {
  export type DomainStruct = {
    owner: AddressLike;
    ipfsHash: string;
    integrityProof: BytesLike;
    expiresAt: BigNumberish;
  };

  export type DomainStructOutput = [
    owner: string,
    ipfsHash: string,
    integrityProof: string,
    expiresAt: bigint
  ] & {
    owner: string;
    ipfsHash: string;
    integrityProof: string;
    expiresAt: bigint;
  };
}

export interface GICRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getDomain"
      | "register"
      | "renewalSeconds"
      | "updateRecords"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "getDomain", values: [string]): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [string, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renewalSeconds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateRecords",
    values: [string, string, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "getDomain", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renewalSeconds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRecords",
    data: BytesLike
  ): Result;
}

export interface GICRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): GICRegistry;
  waitForDeployment(): Promise<this>;

  interface: GICRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getDomain: TypedContractMethod<
    [n: string],
    [GICRegistry.DomainStructOutput],
    "view"
  >;

  register: TypedContractMethod<
    [n: string, c: string, p: BytesLike],
    [void],
    "payable"
  >;

  renewalSeconds: TypedContractMethod<[], [bigint], "view">;

  updateRecords: TypedContractMethod<
    [n: string, c: string, p: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getDomain"
  ): TypedContractMethod<[n: string], [GICRegistry.DomainStructOutput], "view">;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<
    [n: string, c: string, p: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "renewalSeconds"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "updateRecords"
  ): TypedContractMethod<
    [n: string, c: string, p: BytesLike],
    [void],
    "nonpayable"
  >;

  filters: {};
}
