/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as c151 from "./C151";
export type { c151 };
export type { GIC } from "./GIC";
export type { GICGovernor } from "./GICGovernor";
export type { GICRegistry } from "./GICRegistry";
